// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdnAYB5d-QLe-XPxr_NwNtny-QsKKWoE',
    appId: '1:386377151090:web:508c50bb418d53c954c8eb',
    messagingSenderId: '386377151090',
    projectId: 'tyamoapp-94a42',
    authDomain: 'tyamoapp-94a42.firebaseapp.com',
    storageBucket: 'tyamoapp-94a42.appspot.com',
    measurementId: 'G-52HJ35C5V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vgik5-h2sr7nFYTbVb0ozuGm9u5IpYU',
    appId: '1:386377151090:android:5fffb98c5feb2f5654c8eb',
    messagingSenderId: '386377151090',
    projectId: 'tyamoapp-94a42',
    storageBucket: 'tyamoapp-94a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfGbdk92r00LDosglXd8IRRQXWseq5BA',
    appId: '1:386377151090:ios:1e51ba957243688854c8eb',
    messagingSenderId: '386377151090',
    projectId: 'tyamoapp-94a42',
    storageBucket: 'tyamoapp-94a42.appspot.com',
    iosBundleId: 'com.example.tyamoApp',
  );
}
